# Generated by Django 4.2.3 on 2023-07-07 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DataGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Описание графика', max_length=10000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.author')),
            ],
        ),
        migrations.CreateModel(
            name='DataMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Описание карты', max_length=10000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.author')),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип данных: график, карта, др.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FederalDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название ФО', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название региона', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataMapInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID карты', primary_key=True, serialize=False)),
                ('created', models.DateField(blank=True, null=True)),
                ('data_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='maps.datamap')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='maps.region')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='datamap',
            name='data_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.datatype'),
        ),
        migrations.CreateModel(
            name='DataGraphInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID графика', primary_key=True, serialize=False)),
                ('created', models.DateField(blank=True, null=True)),
                ('data_graph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='maps.datagraph')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='maps.region')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='datagraph',
            name='data_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.datatype'),
        ),
    ]
