# Generated by Django 4.2.3 on 2023-07-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_datagraph_user_datagraphinstance_user_datamap_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('geometry', models.CharField(max_length=20000)),
                ('rank', models.CharField(max_length=200)),
                ('federal_subject', models.CharField(max_length=200)),
                ('population_2023_estimate', models.CharField(max_length=200)),
                ('population_2021_census', models.CharField(max_length=200)),
                ('change', models.CharField(max_length=200)),
                ('land_area_km2', models.CharField(max_length=200)),
                ('pop_density_per_km2', models.CharField(max_length=200)),
            ],
        ),
    ]
