# Generated by Django 4.2.3 on 2023-07-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_parcedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcedmodel',
            name='change',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parcedmodel',
            name='federal_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parcedmodel',
            name='land_area_km2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parcedmodel',
            name='pop_density_per_km2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parcedmodel',
            name='population_2021_census',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parcedmodel',
            name='population_2023_estimate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parcedmodel',
            name='rank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
